repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict
      - id: mixed-line-ending
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks: [{ id: shellcheck }]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-4
    hooks: [{ id: shfmt, args: ["-i", "2", "-ci", "-bn"] }]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.8
    hooks: [{ id: ruff, args: ["--fix"] }]
